# Test playbook for the bertvv.rh-base role with role variables set.
#
# The SSH keys for the admin user are stored in tests/sshkey. Check SSH login with e.g.
#
#   ssh -i sshkey/admin_key -p 2222 admin@127.0.0.1
#
# The port number is the forwarded port on the VirtualBox NAT interface that Vagrant also uses to
# connect to the VM.
---

- hosts: all
  become: true
  roles:
    - rh-base
